# Generated by Django 5.1 on 2024-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('father_name', models.CharField(max_length=100, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('marital_status', models.CharField(choices=[('single', 'Turmush qurmagan'), ('married', 'Turmush qurgan'), ('devorced', 'Ajrashgan')], max_length=20, verbose_name='Oilaviy xolatingiz')),
                ('education_institution', models.CharField(max_length=200, verbose_name="Ta'lim muassasalari nomi va bitirgan yilingiz")),
                ('height_weight', models.CharField(max_length=20, verbose_name="Bo'y va vazningiz (sm/kg)")),
                ('is_student', models.BooleanField(default=False, verbose_name='Siz hozirda qaysidir universitet, litsey yoki kollej talabasimisiz?')),
                ('languages', models.TextField(blank=True, verbose_name='Qaysi tillarni bilasiz?')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat (Haqiqiy turar joy)')),
                ('city_district', models.CharField(max_length=100, verbose_name='Shaxar/Tuman (Haqiqiy turar joy)')),
                ('address', models.CharField(max_length=200, verbose_name="Manzilingiz (MFY, ko'cha)")),
                ('desired_branch', models.CharField(max_length=100, verbose_name='Qaysi filialda ishlashni xohlaysiz?')),
                ('desired_position', models.CharField(max_length=100, verbose_name='Qaysi lavozimda ishlashni xohlaysiz?')),
                ('worked_before', models.BooleanField(default=False, verbose_name='Avval bizning kompaniyamizda ishlaganmisiz?')),
                ('is_citizen', models.BooleanField(default=True, verbose_name="O'zbekiston Respublikasi fuqarosimisiz?")),
                ('is_employed', models.BooleanField(default=False, verbose_name="Hozirda ish bilan ta'minlangamisiz?")),
                ('relative_in_company', models.BooleanField(default=False, verbose_name='Bizdang kompaniyada ishlaydigan yaqin qarindoshingiz bormi?')),
                ('software_skills', models.TextField(blank=True, verbose_name='Qaysi dasturlardan foydalana olasiz?')),
                ('health_info', models.TextField(blank=True, verbose_name="Sog'ligingiz xaqida ma'lumotlar")),
                ('last_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Oxirgi ish joyida olgan ish xaqingiz (so'm)?")),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Qancha maosh olishni xohlaysiz (so'm)?")),
                ('has_personal_car', models.BooleanField(default=False, verbose_name='Shaxsiy avtomobilingiz bormi?')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Avtomabilingiz rusumi')),
                ('can_travel', models.BooleanField(default=False, verbose_name='Xizmat safariga bora olasizmi?')),
                ('job_source', models.CharField(max_length=200, verbose_name="Bo'sh ish o'rni haqida qayerdan bildingiz?")),
                ('has_criminal_record', models.BooleanField(default=False, verbose_name='Sudlanganmisiz?')),
                ('criminal_record_details', models.TextField(blank=True, verbose_name="Sudlanganligingiz (Qaysi moddalar bo'yicha)")),
                ('additional_phone', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon raqam")),
                ('personal_photo', models.ImageField(upload_to='Project/photos/', verbose_name='Shaxsiy rasmingiz *')),
                ('passport_type', models.CharField(choices=[('passport', 'Pasport'), ('id_card', 'ID karta')], max_length=20, verbose_name='Pasport turi')),
                ('passport_photo', models.ImageField(upload_to='Project/passport_photos/', verbose_name='Pasport rasmi (yoki ID card)')),
                ('id_card_back_photo', models.ImageField(upload_to='Project/id_card_back_photos/', verbose_name='ID card orqa tomon rasmi')),
                ('consent', models.BooleanField(default=False, verbose_name='Roziman * (Rozilik shartlari bilan tanishish)')),
            ],
        ),
    ]
