# Generated by Django 5.1 on 2024-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0002_remove_questionnaire_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='id_card_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='ID card orqa tomon rasmi'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_card_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='ID card old tomon rasmi'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='Pasport rasmi (yoki ID card)'),
        ),
    ]
