# Generated by Django 5.1 on 2024-09-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0002_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Anketalar'},
        ),
        migrations.AlterModelTable(
            name='questionnaire',
            table='questionnaire',
        ),
    ]
