# Generated by Django 5.1 on 2024-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0003_alter_questionnaire_id_card_back_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='Shaxsiy rasmingiz *'),
        ),
    ]
