# Generated by Django 5.1 on 2024-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0003_alter_questionnaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
