# Generated by Django 5.1 on 2024-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0004_questionnaire_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Familiya')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
