# Generated by Django 5.1 on 2024-09-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0005_application_delete_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Anketalar'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
