# Generated by Django 5.1 on 2024-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0007_alter_application_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('marital_status', models.CharField(max_length=221)),
                ('education_institutions', models.CharField(max_length=200, verbose_name="Ta'lim muassasalari nomi va bitirgan yilingiz")),
                ('height_weight', models.CharField(max_length=20, verbose_name="Bo'y va vazningiz (sm/kg)")),
                ('is_student', models.BooleanField(default=False, verbose_name='Siz hozirda qaysidir universitet, litsey yoki kollej talabasimisiz?')),
                ('languages', models.TextField(blank=True, verbose_name='Qaysi tillarni bilasiz? va qaq darajada')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat (Haqiqiy turar joy)')),
                ('city_district', models.CharField(max_length=100, verbose_name='Shaxar/Tuman (Haqiqiy turar joy)')),
                ('address', models.CharField(max_length=200, verbose_name="Manzilingiz (MFY, ko'cha)")),
                ('desired_branch', models.CharField(max_length=100, verbose_name='Qaysi filialda ishlashni xohlaysiz?')),
                ('desired_position', models.CharField(max_length=100, verbose_name='Qaysi lavozimda ishlashni xohlaysiz?')),
                ('worked_before', models.BooleanField(default=False, verbose_name='Avval bizning kompaniyamizda ishlaganmisiz?')),
                ('is_citizen', models.BooleanField(default=True, verbose_name="O'zbekiston Respublikasi fuqarosimisiz?")),
                ('is_employed', models.BooleanField(default=False, verbose_name="Hozirda ish bilan ta'minlangamisiz?")),
                ('relative_in_company', models.BooleanField(default=False, verbose_name='Bizdang kompaniyada ishlaydigan yaqin qarindoshingiz bormi?')),
                ('software_skills', models.TextField(blank=True, verbose_name='Qaysi dasturlardan foydalana olasiz? va qay darajada')),
                ('health_info', models.TextField(blank=True, verbose_name="Sog'ligingiz xaqida ma'lumotlar")),
                ('last_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Oxirgi ish joyida olgan ish xaqingiz (so'm)?")),
                ('desired_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Qancha maosh olishni xohlaysiz (so'm)?")),
                ('has_personal_car', models.BooleanField(default=False, verbose_name='Shaxsiy avtomobilingiz bormi?')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Avtomabilingiz rusumi')),
                ('can_travel', models.BooleanField(default=False, verbose_name='Xizmat safariga bora olasizmi?')),
                ('job_source', models.CharField(max_length=200, verbose_name="Bo'sh ish o'rni haqida qayerdan bildingiz?")),
                ('working_period', models.CharField(max_length=500, verbose_name='Bizning kompaniyada qancha vaqt mobaynida ishlamoqchisiz?')),
                ('has_criminal_record', models.BooleanField(default=False, verbose_name='Sudlanganmisiz?')),
                ('criminal_record_details', models.TextField(blank=True, verbose_name="Sudlanganligingiz (Qaysi moddalar bo'yicha)")),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Shaxsiy telefon raqam')),
                ('additional_phone', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon raqam")),
                ('personal_photo', models.ImageField(upload_to='Project/photos/', verbose_name='Shaxsiy rasmingiz *')),
                ('family_member', models.TextField(verbose_name="Oila a'zolari haqida ma'lumotlar")),
                ('passport_type', models.CharField(max_length=20, verbose_name='Pasport turi')),
                ('passport_image', models.ImageField(upload_to='Project/passport_photos/', verbose_name='Pasport rasmi (yoki ID card)')),
                ('id_card_back_photo', models.ImageField(upload_to='Project/id_card_back_photos/', verbose_name='ID card orqa tomon rasmi')),
                ('id_card_front_photo', models.ImageField(upload_to='Project/id_card_front_photos/')),
                ('difficulty', models.CharField(max_length=20, verbose_name='Anketaning qiyinlik darajasi')),
                ('consent', models.BooleanField(default=False, verbose_name='Roziman * (Rozilik shartlari bilan tanishish)')),
                ('response', models.CharField(blank=True, max_length=500, null=True, verbose_name="Agar 10 kun davomida sizga qayta aloqaga chiqmasak bu lavozimga ehtiyojimiz yo'qligini bildiradi. Tanlang:")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Anketalar',
                'db_table': 'questionnaire',
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
