# Generated by Django 5.1 on 2024-09-26 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0008_questionnaire_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='previous_job',
            field=models.CharField(default=django.utils.timezone.now, max_length=221, verbose_name='Ilgari biror joyda ishlaganmisiz?'),
            preserve_default=False,
        ),
    ]
