# Generated by Django 5.1 on 2024-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anketa', '0010_remove_questionnaire_criminal_record_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='car_model',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Qancha maosh olishni xohlaysiz (so'm)?"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_card_back_photo',
            field=models.ImageField(upload_to='temp/', verbose_name='ID card orqa tomon rasmi'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_card_front_photo',
            field=models.ImageField(upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='last_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Oxirgi ish joyida olgan ish xaqingiz (so'm)?"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='passport_image',
            field=models.ImageField(upload_to='temp/', verbose_name='Pasport rasmi (yoki ID card)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='personal_photo',
            field=models.ImageField(upload_to='temp/', verbose_name='Shaxsiy rasmingiz *'),
        ),
    ]
